ideologies = [
        {
                "name": "Pinochetism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 0,
                    "prag": 0,
                    "pac": 0,
                    "red": 100,
                    "anarchy": 0,
                    "dem": 0,
                    "sec": 30,
                    "assoc": 0,
                    "glob": 20,
                    "imp": 70,
                    "mult": 0,
                    "queer": 0,
                    "work": 100,
                    "priv": 70,
                    "nfree": 0
                }
        },
        {
                "name": "Third Way",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 60,
                    "prag": 100,
                    "pac": 20,
                    "red": 75,
                    "anarchy": 30,
                    "dem": 65,
                    "sec": 50,
                    "assoc": 50,
                    "glob": 100,
                    "imp": 100,
                    "mult": 60,
                    "queer": 40,
                    "biocon": 80,
                    "ludd": 0,
                    "work": 100,
                    "priv": 70
                }
        },
        {
                "name": "Machiavelianism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 0,
                    "prag": 100,
                    "pac": 0,
                    "red": 100,
                    "anarchy": 0,
                    "dem": 0,
                    "sec": 50,
                    "assoc": 0,
                    "glob": 50,
                    "imp": 100,
                    "mult": 50,
                    "queer": 50,
                    "biocon": 50,
                    "ludd": 50,
                    "work": 100,
                    "priv": 100
                }
        },
        {
                "name": "Anarcho-Xeno-Feminism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 50,
                    "coll": 100,
                    "prag": 20,
                    "pac": 20,
                    "red": 0,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 100,
                    "assoc": 50,
                    "glob": 100,
                    "imp": 0,
                    "mult": 100,
                    "queer": 100,
                    "biocon": 0,
                    "ludd": 0,
                    "work": 30,
                    "priv": 0
                }
        },
        {
                "name": "Capitalist Transhumanism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 0,
                    "prag": 100,
                    "pac": 40,
                    "red": 85,
                    "anarchy": 65,
                    "dem": 0,
                    "sec": 100,
                    "assoc": 85,
                    "glob": 100,
                    "imp": 80,
                    "mult": 75,
                    "queer": 60,
                    "biocon": 0,
                    "ludd": 0,
                    "work": 90,
                    "priv": 100
                }
        },
        {
                "name": "Ba'athism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 85,
                    "coll": 70,
                    "prag": 20,
                    "pac": 0,
                    "red": 85,
                    "anarchy": 0,
                    "dem": 15,
                    "sec": 80,
                    "assoc": 0,
                    "glob": 0,
                    "imp": 55,
                    "mult": 0,
                    "queer": 0,
                    "biocon": 100,
                    "ludd": 60,
                    "work": 90,
                    "priv": 0
                }
        },
        {
                "name": "Anarcho-distributism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 65,
                    "coll": 70,
                    "prag": 80,
                    "pac": 50,
                    "red": 32,
                    "anarchy": 80,
                    "dem": 90,
                    "sec": 50,
                    "assoc": 55,
                    "glob": 100,
                    "imp": 0,
                    "mult": 90,
                    "queer": 60,
                    "biocon": 60,
                    "ludd": 15,
                    "work": 40,
                    "priv": 0
                }
        },
        {
                "name": "Modern Theosocialism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 85,
                    "coll": 100,
                    "prag": 25,
                    "pac": 50,
                    "red": 65,
                    "anarchy": 25,
                    "dem": 35,
                    "sec": 0,
                    "assoc": 0,
                    "glob": 50,
                    "imp": 85,
                    "mult": 35,
                    "queer": 0,
                    "biocon": 100,
                    "ludd": 50,
                    "work": 95,
                    "priv": 0
                }
        },
        {
                "name": "Anarcho-primitivism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 20,
                    "coll": 100,
                    "prag": 15,
                    "pac": 20,
                    "red": 85,
                    "anarchy": 100,
                    "dem": 85,
                    "sec": 75,
                    "assoc": 100,
                    "glob": 0,
                    "imp": 0,
                    "mult": 0,
                    "queer": 65,
                    "biocon": 100,
                    "ludd": 100,
                    "work": 0,
                    "priv": 0
                }
        },
        {
                "name": "Koinoianism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 85,
                    "coll": 100,
                    "prag": 0,
                    "pac": 35,
                    "red": 100,
                    "anarchy": 60,
                    "dem": 15,
                    "sec": 0,
                    "assoc": 100,
                    "glob": 50,
                    "imp": 80,
                    "mult": 0,
                    "queer": 10,
                    "biocon": 100,
                    "ludd": 45,
                    "work": 100,
                    "priv": 65
                }
        },
        {
                "name": "Eco-Communalism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 10,
                    "coll": 100,
                    "prag": 0,
                    "pac": 35,
                    "red": 15,
                    "anarchy": 80,
                    "dem": 80,
                    "sec": 50,
                    "assoc": 100,
                    "glob": 100,
                    "imp": 0,
                    "mult": 55,
                    "queer": 65,
                    "biocon": 60,
                    "ludd": 50,
                    "work": 50,
                    "priv": 0,
                    "nfree": 100
                }
        },
        {
                "name": "Earth Liberation",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 0,
                    "coll": 90,
                    "prag": 75,
                    "pac": 10,
                    "red": 25,
                    "anarchy": 85,
                    "dem": 90,
                    "sec": 70,
                    "assoc": 50,
                    "glob": 100,
                    "imp": 15,
                    "mult": 70,
                    "queer": 80,
                    "biocon": 50,
                    "ludd": 50,
                    "work": 50,
                    "priv": 20
                }
        },
        {
                "name": "Indigenismo",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 65,
                    "coll": 30,
                    "prag": 40,
                    "pac": 90,
                    "red": 55,
                    "anarchy": 25,
                    "dem": 60,
                    "sec": 50,
                    "assoc": 35,
                    "glob": 50,
                    "imp": 0,
                    "mult": 100,
                    "queer": 30,
                    "biocon": 100,
                    "ludd": 65,
                    "work": 95,
                    "priv": 35
                }
        },
        {
                "name": "Veganarchism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 0,
                    "coll": 100,
                    "prag": 25,
                    "pac": 10,
                    "red": 0,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 100,
                    "assoc": 100,
                    "glob": 50,
                    "imp": 0,
                    "mult": 100,
                    "queer": 100,
                    "biocon": 50,
                    "ludd": 0,
                    "work": 35,
                    "priv": 0
                }
        },
        {
                "name": "Technogaianism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 0,
                    "coll": 70,
                    "prag": 0,
                    "pac": 70,
                    "red": 0,
                    "anarchy": 90,
                    "dem": 100,
                    "sec": 50,
                    "assoc": 75,
                    "glob": 80,
                    "imp": 0,
                    "mult": 100,
                    "queer": 100,
                    "biocon": 10,
                    "ludd": 0,
                    "work": 0,
                    "priv": 30
                }
        },
        {
                "name": "Anarchotranshumanism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 50,
                    "prag": 40,
                    "pac": 90,
                    "red": 15,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 100,
                    "assoc": 100,
                    "glob": 100,
                    "imp": 0,
                    "mult": 50,
                    "queer": 100,
                    "biocon": 0,
                    "ludd": 0,
                    "work": 0,
                    "priv": 15
                }
        },
        {
                "name": "Technoprogressivism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 55,
                    "coll": 50,
                    "prag": 100,
                    "pac": 50,
                    "red": 35,
                    "anarchy": 50,
                    "dem": 65,
                    "sec": 100,
                    "assoc": 40,
                    "glob": 100,
                    "imp": 40,
                    "mult": 80,
                    "queer": 80,
                    "biocon": 0,
                    "ludd": 0,
                    "work": 40,
                    "priv": 50
                }
        },
        {
                "name": "Panarchy",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 60,
                    "coll": 100,
                    "prag": 90,
                    "pac": 0,
                    "red": 0,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 100,
                    "assoc": 100,
                    "glob": 100,
                    "imp": 0,
                    "mult": 100,
                    "queer": 100,
                    "biocon": 0,
                    "ludd": 0,
                    "work": 0,
                    "priv": 0
                }
       },
       {
                "name": "Post-Leftism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 20,
                    "coll": 50,
                    "prag": 90,
                    "pac": 0,
                    "red": 60,
                    "anarchy": 100,
                    "dem": 90,
                    "sec": 100,
                    "assoc": 100,
                    "glob": 75,
                    "imp": 0,
                    "mult": 90,
                    "queer": 85,
                    "biocon": 15,
                    "ludd": 0,
                    "work": 0,
                    "priv": 30
                }
        },    
        {
                "name": "Pink Anarchism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 50,
                    "coll": 65,
                    "prag": 10,
                    "pac": 10,
                    "red": 20,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 90,
                    "assoc": 100,
                    "glob": 100,
                    "imp": 15,
                    "mult": 70,
                    "queer": 100,
                    "biocon": 25,
                    "ludd": 25,
                    "work": 50,
                    "priv": 10
                }
            },
        {
                "name": "Neozapatismo",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 85,
                    "coll": 100,
                    "prag": 100,
                    "pac": 0,
                    "red": 10,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 80,
                    "assoc": 100,
                    "glob": 90,
                    "imp": 0,
                    "mult": 75,
                    "queer": 45,
                    "biocon": 40,
                    "ludd": 80,
                    "work": 10,
                    "priv": 0
                }
            },
        {
                "name": "Magonismo",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 92,
                    "coll": 75,
                    "prag": 10,
                    "pac": 30,
                    "red": 60,
                    "anarchy": 78,
                    "dem": 90,
                    "sec": 100,
                    "assoc": 100,
                    "glob": 0,
                    "imp": 0,
                    "mult": 80,
                    "queer": 30,
                    "biocon": 90,
                    "ludd": 70,
                    "work": 90,
                    "priv": 30
                }
        },
        {
                "name": "Kibbutzism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 90,
                    "coll": 100,
                    "prag": 80,
                    "pac": 20,
                    "red": 90,
                    "anarchy": 90,
                    "dem": 74,
                    "sec": 31,
                    "assoc": 100,
                    "glob": 0,
                    "imp": 85,
                    "mult": 15,
                    "queer": 0,
                    "biocon": 100,
                    "ludd": 91,
                    "work": 100,
                    "priv": 0
                }
        },
        {
                "name": "Abahlali baseMjondolo",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 70,
                    "coll": 100,
                    "prag": 80,
                    "pac": 50,
                    "red": 10,
                    "anarchy": 80,
                    "dem": 100,
                    "sec": 60,
                    "assoc": 100,
                    "glob": 50,
                    "imp": 10,
                    "mult": 80,
                    "queer": 60,
                    "biocon": 70,
                    "ludd": 50,
                    "work": 30,
                    "priv": 0
                }
        },
        {
                "name": "Bioregionalism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 30,
                    "coll": 70,
                    "prag": 20,
                    "pac": 10,
                    "red": 50,
                    "anarchy": 50,
                    "dem": 88,
                    "sec": 50,
                    "assoc": 70,
                    "glob": 30,
                    "imp": 0,
                    "mult": 50,
                    "queer": 50,
                    "biocon": 68,
                    "ludd": 76,
                    "work": 30,
                    "priv": 40
                }
        },
        {
                "name": "Ubuntu",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 50,
                    "coll": 100,
                    "prag": 30,
                    "pac": 80,
                    "red": 40,
                    "anarchy": 75,
                    "dem": 85,
                    "sec": 40,
                    "assoc": 92,
                    "glob": 60,
                    "imp": 10,
                    "mult": 30,
                    "queer": 50,
                    "biocon": 50,
                    "ludd": 68,
                    "priv": 15
                }
        },
        {
                "name": "Bennism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 44,
                    "coll": 80,
                    "prag": 45,
                    "pac": 95,
                    "red": 40,
                    "anarchy": 35,
                    "dem": 60,
                    "sec": 45,
                    "assoc": 50,
                    "glob": 45,
                    "imp": 15,
                    "mult": 60,
                    "queer": 60,
                    "work": 90,
                    "priv": 25
                }
        },
        {
                "name": "Titoism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 100,
                    "prag": 80,
                    "pac": 10,
                    "red": 100,
                    "anarchy": 0,
                    "dem": 0,
                    "sec": 100,
                    "assoc": 20,
                    "glob": 55,
                    "imp": 50,
                    "mult": 0,
                    "queer": 0,
                    "work": 100,
                    "priv": 0
                }
        },
        {
                "name": "Geoanarchism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 46,
                    "coll": 29,
                    "prag": 49,
                    "red": 40,
                    "anarchy": 100,
                    "dem": 100,
                    "assoc": 100,
                    "mult": 60,
                    "queer": 50,
                    "work": 100,
                    "priv": 0
                }
        },
        {
                "name": "Geolibertarianism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 46,
                    "coll": 0,
                    "prag": 50,
                    "red": 40,
                    "anarchy": 70,
                    "dem": 70,
                    "assoc": 70,
                    "mult": 60,
                    "queer": 50,
                    "work": 100,
                    "priv": 0
                }
        },
        {
                "name": "Social Georgism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 46,
                    "coll": 40,
                    "prag": 60,
                    "red": 40,
                    "anarchy": 40,
                    "dem": 70,
                    "assoc": 60, 
                    "mult": 60,
                    "queer": 50,
                    "work": 100,
                    "priv": 0
                }
        },
        {
                "name": "Georgism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 46,
                    "coll": 30,
                    "prag": 60,
                    "red": 40,
                    "anarchy": 50,
                    "dem": 70,
                    "assoc": 60,
                    "mult": 60,
                    "queer": 50,
                    "work": 100,
                    "priv": 0
                }
        },
        {
                "name": "Caudillismo",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 85,
                    "coll": 20,
                    "prag": 15,
                    "pac": 20,
                    "red": 85,
                    "anarchy": 60,
                    "dem": 10,
                    "sec": 30,
                    "assoc": 0,
                    "glob": 0,
                    "imp": 15,
                    "mult": 10
                }
      }, 
      {
                "name": "Technocracy",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 0,
                    "prag": 100,
                    "red": 100,
                    "anarchy": 0,
                    "dem": 0,
                    "sec": 100,
                    "assoc": 0,
                    "glob": 100,
                    "biocon": 20,
                    "ludd": 0
                }
        },
        {
                "name": "Ochlocarchy",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100,
                    "coll": 100,
                    "prag": 0,
                    "pac": 0,
                    "red": 100,
                    "anarchy": 100,
                    "dem": 80,
                    "free": 0
                }
        },
        {
                "name": "Urbism",
                "link": "",
                "desc": "",
                "stats": {
                    "coll": 90,
                    "prag": 50,
                    "pac": 100,
                    "red": 50,
                    "anarchy": 30,
                    "assoc": 85,
                    "glob": 0,
                    "imp": 0,
                    "mult": 30
                }
        },
        {
                "name": "Anarcho-Communism",
                "link": "",
                "desc": "",
                "stats": {
                    "coll": 100,
                    "pac": 60,
                    "anarchy": 100,
                    "dem": 100,
                    "red": 10,
                    "queer": 90,
                    "mult": 90,
                    "imp": 10,
                    "priv": 0
                }
        },
        {
                "name": "Anarcho-Capitalism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 90
                    "coll": 30,
                    "prag": 75,
                    "red": 80,
                    "anarchy": 100,
                    "dem": 10,
                    "assoc": 100,
                    "priv": 100
                }
        },
        {
                "name": "Egoism",
                "link": "",
                "desc": "",
                "stats": {
                    "dom": 100  
                    "coll": 0,
                    "red:" 100,
                    "prag": 0,
                    "anarchy": 100,
                    "dem": 100,
                    "sec": 100,
                    "assoc": 100,
                    "work": 0,
                    "priv": 100
                }
       }
];
