ideologies = [
  {
        "name": "Neozapatismo",
        "stats": {
            "dom": 85,
            "coll": 100,
            "prag": 100,
            "pac": 0,
            "red": 10,
            "anarchy": 100,
            "dem": 100,
            "sec": 80,
            "assoc": 100,
            "glob": 90,
            "imp": 0,
            "mult": 75,
            "queer": 45,
            "biocon": 40,
            "ludd": 80,
            "work": 10,
        }
    },
      {
        "name": "Magonismo",
        "stats": {
            "dom": 92,
            "coll": 75,
            "prag": 10,
            "pac": 30,
            "red": 60,
            "anarchy": 78,
            "dem": 90,
            "sec": 100,
            "assoc": 100,
            "glob": 0,
            "imp": 0,
            "mult": 80,
            "queer": 30,
            "biocon": 90,
            "ludd": 70,
            "work": 90,
        }
    },
      {
        "name": "Kibbutzism",
        "stats": {
            "dom": 90,
            "coll": 100,
            "prag": 80,
            "pac": 20,
            "red": 90,
            "anarchy": 90,
            "dem": 74,
            "sec": 31,
            "assoc": 100,
            "glob": 0,
            "imp": 85,
            "mult": 15,
            "queer": 0,
            "biocon": 100,
            "ludd": 91,
            "work": 100,
        }
    },
  {
        "name": "Abahlali baseMjondolo",
        "stats": {
            "dom": 70,
            "coll": 100,
            "prag": 80,
            "pac": 50,
            "red": 10,
            "anarchy": 80,
            "dem": 100,
            "sec": 60,
            "assoc": 100,
            "glob": 50,
            "imp": 10,
            "mult": 80,
            "queer": 50,
            "biocon": 70,
            "ludd": 50,
            "work": 30,
        }
    },
      {
        "name": "Bioregionalism",
        "stats": {
            "dom": 30,
            "coll": 70,
            "prag": 20,
            "pac": 10,
            "red": 50,
            "anarchy": 50,
            "dem": 88,
            "sec": 50,
            "assoc": 70,
            "glob": 30,
            "imp": 0,
            "mult": 50,
            "queer": 50,
            "biocon": 68,
            "ludd": 76,
            "work": 30,
        }
    },
  {
        "name": "Ubuntu",
        "stats": {
            "dom": 50,
            "coll": 100,
            "prag": 30,
            "pac": 80,
            "red": 40,
            "anarchy": 75,
            "dem": 85,
            "sec": 40,
            "assoc": 92,
            "glob": 60,
            "imp": 10,
            "mult": 30,
            "queer": 50,
            "biocon": 50,
            "ludd": 68,
        }
    },
     {
        "name": "Bennism",
        "stats": {
            "dom": 44,
            "coll": 80,
            "prag": 45,
            "pac": 95,
            "red": 40,
            "anarchy": 35,
            "dem": 60,
            "sec": 45,
            "assoc": 50,
            "glob": 45,
            "imp": 15,
            "mult": 60,
            "queer": 60,
            "work": 90,
        }
    },
    
        "name": "Anarcho-Communism",
        "stats": {
            "coll": 100,
            "pac": 60,
            "anarchy": 100,
            "dem": 100,
            "red": 10,
            "queer": 90,
            "mult": 90,
            "imp": 10,
        }
    },
      {
        "name": "Anarcho-Capitalism",
        "stats": {
          "dom": 90
          "coll": 30,
            "prag": 75,
            "anarchy": 100,
            "dem": 10,
            "assoc": 100,
        }
    },
    {
        "name": "Egoism",
        "stats": {
          "dom": 100  
          "coll": 0,
            "red:" 100,
            "prag": 0,
            "anarchy": 100,
            "dem": 100,
            "sec": 100,
            "assoc": 100,
            "work": 0,
        }
    },
];
