questions = 
    [[//Dominionist <-> Sentientist
        [//4
            "Empathy and consideration should only extend as far as other human beings.",
            "Humans are separate from the natural world, and 'above' it.",
            "Any given biome's greatest value is what humanity can do with it.",
        ],
        [//3
            "Humans are the most intelligent/advanced species on Earth. This makes us its owners.",
            "Raising and killing animals for clothing, materials, and food is natural and, therefore, not exploitation.",
            "If there is a resource (living or otherwise) to be exploited, the people around it should do their best to exploit it, regardless of any ecological factors."
        ],
        [//2
            "Climate change / global warming is a necessary price of progress.",
            "Irreversibly transforming ecosystems with the main goal of increasing the quality of life of human beings is acceptable, or even something to strive toward.",
            "Protections for animals or ecosystems are unnecessary, and stand in the way of human development."
        ],
        [//1
            "Climate change isn't real, or at least isn't caused by human activity.",
            "Animal rights activists are dangerous, and should be classified as terrorists.",
            "Human survival is the only reason climate change is worth fighting."
        ],
        [//-1
            "There should be protections in place to ensure the preservation of endangered species.",
            "Humanity should do everything in its power to restore the ecosystems we've already damaged.",
            "No more wild land should be developed, repurposed, or farmed than is absolutely necessary."
        ],
        [//-2
            "Climate change and the preservation (and restoration) of Earth's biodiversity should be a top-level priority for everyone.",
            "All sentient beings have inherent worth, beyond the benefit of humanity.",
            "Forest logging, hunting, and similar living-resource-extraction activities should be stopped altogether."
        ],
        [//-3
            "Eliminating harm to all entities (human and otherwise) and their habitats should be a priority in all human endeavors.",
            "Humans should neither eat nor exploit animals in any way.",
            "Using, consuming, or producing any product made from a sentient being is unethical."
        ],
        [//-4
            "It is unacceptable for human actions to lead to the destruction or extinction of any part of an ecosystem.",
            "Animal agriculture should be completely abolished.",
            "We can never achieve true liberation until we consider non-human sentient beings as worthy of the same."
        ]],
    [[//Collectivist <-> Individualist
        [//4
            "What matters most about a person is the impact they have on other people.",
            "People are defined by the society around them, and the social groups they belong to.",
            "The effect the decisions one makes have on others should always be the main decisive factor."
        ],
        [//3
            "The needs of the many outweigh the needs of the individual.",
            "No one is self-made; we are all dependent on and shaped by our community.",
            "Crediting only individuals is akin to lying; anything achieved by a group was achieved by everyone who contributed."
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Pragmatist <-> Dogmatist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Pacifist <-> Bellicist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Reductionist <-> Intersectionalist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Anarchist <-> Hierarchist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Democrat <-> Vanguardist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
     [[//Secularist <-> Clericalist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Free Associate <-> Unitarian
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Globalist <-> Autarkist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Imperialist <-> Anticolonialist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Multiculturalist <-> Assimilationist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Queer Liberation <-> Bioessentialist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "Humans are divided into only 2 sexes, which are biologically 'designed' for heterosexuality.",
            "",
            ""
        ],
        [//-4
            "The traits associated with masculinity and femininity stem directly from biological characteristics.",
            "",
            ""
        ]],
    [[//Bioconservative <-> Transhumanist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Luddism <-> Technophilia
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Post-Work <-> Labor Essentialist
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
     [[//Communal Property <-> Private Property
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
    [[//Negative Freedoms <-> Positive Freedoms
        [//4
            "",
            "",
            ""
        ],
        [//3
            "",
            "",
            ""
        ],
        [//2
            "",
            "",
            ""
            
        ],
        [//1
            "",
            "",
            ""
        ],
        [//-1
            "",
            "",
            ""
        ],
        [//-2
            "",
            "",
            ""
        ],
        [//-3
            "",
            "",
            ""
        ],
        [//-4
            "",
            "",
            ""
        ]],
